# Makefile
# RTL testbench with tb.v and combined project.v

SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
PROJECT_SOURCES = project.v

ifneq ($(GATES),yes)

# RTL simulation
SIM_BUILD        = sim_build/rtl
VERILOG_SOURCES += $(SRC_DIR)/$(PROJECT_SOURCES) \
                   $(PWD)/tb.v

else

# Gate level simulation
SIM_BUILD        = sim_build/gl
COMPILE_ARGS    += -DGL_TEST
COMPILE_ARGS    += -DFUNCTIONAL
COMPILE_ARGS    += -DUSE_POWER_PINS
COMPILE_ARGS    += -DSIM
COMPILE_ARGS    += -DUNIT_DELAY=\#1
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/primitives.v
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v

endif

# Allow sharing configuration between design and testbench via `include`
COMPILE_ARGS    += -I$(SRC_DIR)

# Top module is your Verilog testbench
TOPLEVEL = tb

# MODULE is the basename of the Python test file (used if you also want cocotb)
MODULE = test

# Include cocotb rules
include $(shell cocotb-config --makefiles)/Makefile.sim
